# Generated by Django 4.1.7 on 2023-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
        migrations.AddField(
            model_name='data',
            name='soilmoisture',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='temp',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
