# Generated by Django 4.1.7 on 2023-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_data_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='humidity',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='phlevel',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='pressure',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
